### ISSUE TITLE
I get an error when executing documentation code

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-EMX-downloader#9]
<img width="1120" alt="screen shot 2017-01-31 at 17 45 49" src="https://cloud.githubusercontent.com/assets/120060/22474764/2c7c2192-e7dd-11e6-9994-88d54bd07aa6.png">

**Comment by bartcharbon** [comment]
Strange, when executing exactly the same I get:
"An error occurred: JSONObject["meta"] not found."
The message should be improved, what it means in this case is that the entity does not exist.

The JNI error does not occur, we need to investigate.

**Comment by bartcharbon** [comment]
The jar did not contain all the dependencies (but it resolves those on the system it was build on).
New release (1.1) is available
